
/** Problem 29 http://projecteuler.net/problem=29
  * "How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?"
  */

object Problem29 extends App {
  val hi = 100
  
  println(distinctPowers(hi).length)
  
  def distinctPowers(hiPower: Int) = 
    (for {
      a <- 2 to hiPower
      b <- 2 to hiPower
    } yield pow(a, b)).distinct

  @scala.annotation.tailrec
  def pow(a: Int, b: Int, result: BigInt = 1): BigInt = 
    if (b == 1)
      a * result
    else
      pow(a, b - 1, a * result)   
}